#!/bin/bash
#
# Script to generate a bunch of passwords in a row of random length.
# The password you subsequently select from that list makes the password even more unpredictable.
#
# SPDX-License-Identifier: Apache-2.0
# FileCopyrightText: <text> 2022-2025 Matthew Buchanan Astley (mbastley@gmail.com, matthewbuchanan@astley.nl) </text>
#


function prw { 

  for i in `seq 1 $(shuf -n 1  -i 1-100)`
    do 
       ./vop $pwl ;
    done 

}

if [ -n "$1" ] ; then
    pwl=$1 
    prw pwl
else
    echo "Please provide a number"
fi
