#!/bin/bash
#
# Script to generate a bunch of passwords in a row of random length.
# The password you subsequently select from that list makes the password even more unpredictable.
#
# SPDX-License-Identifier: Apache-2.0
# FileCopyrightText: <text> 2022-2025 Matthew Buchanan Astley (mbastley@gmail.com, matthewbuchanan@astley.nl) </text>
#



function prw { 

  if [ $tool == 'vops' ] ; then
      for i in `seq 1 $(shuf -n 1  -i 1-100)`
        do
          ./vop -s $pwl $len ;
        done
  else
      for i in `seq 1 $(shuf -n 1  -i 1-100)`
        do 
          ./$tool $pwl ;
        done 
  fi

}

if [ -z $1 ] || [ -z $2 ] ; then
    echo "Please provide a tool and a number"
    exit 1
fi

tool=$1
pwl=$2 
len=$3

case $tool in 
    vop)
       prw $tool $pwl
    ;; 
    t3)
       prw $tool $pwl
    ;; 
    vops)
       prw $tool $len $pwl
       
esac
        



