#!/usr/bin/python3
#
# FileCopyrightText: <text> 2025 Matthew Buchanan Astley (mbastley@gmail.com, matthewbuchanan@astley.nl), with A.I. </text> 
# SPDX-License-Identifier: Apache-2.0
#
# A version that outputs even more special characters, made together with ChatGPT.
# It introduces more entropy to the password and more issues with other tools.
# Apparently wc has an issue with these characters this
# results in an exaggerated character count. I catapult fixing wc somewhere on the todo list.
# The Kolmogorov Smirnov test also has issues with the exotic characters.

import sys
import secrets 
import argparse

class more_special_characters():

    a1 = secrets.SystemRandom("/dev/urandom")
    latin1_printable = [chr(c) for c in list(range(32, 127)) + list(range(160, 256))]

    def replace_non_printables(char_list):
        return [
            c if c in more_special_characters.latin1_printable else more_special_characters.a1.choice(more_special_characters.latin1_printable)
            for c in char_list
        ]

    def remove_spaces(char_list):
        # Remove spaces
        filtered_chars = [c for c in char_list if c.isprintable() and not c.isspace()]
        return(filtered_chars)

    def r3(self):

        a = []

        # Generate requested amount of random bytes  
        random_bytes = bytes([more_special_characters.a1.randint(0, 255) for _ in range(self)])
        char_string = random_bytes.decode('latin1')  # One-to-one byte-to-char
        for i in char_string:
            a.append(i)

        # Collect printable characters and remove spaces
        cleaned = [c for c in a if c.isprintable() and not c.isspace()]

        # Create latin1_printable list of printable characters  
        latin1_printable = [chr(c) for c in list(range(32, 127)) + list(range(160, 256))]

        if len(cleaned) < self:
            # Pad with random printable characters and remove spaces again
            cleaned += [more_special_characters.a1.choice(more_special_characters.remove_spaces(latin1_printable)) for _ in range(self - len(cleaned)) ]
            #cleaned = more_special_characters.remove_spaces(cleaned)
        elif len(cleaned) > self:
            # Truncate and remove spaces
            cleaned = more_special_characters.remove_spaces(cleaned)
            cleaned = cleaned[:self]

        return ''.join(cleaned)
      
if __name__ == '__main__':
  
    parser = argparse.ArgumentParser()
    parser.add_argument('Password_Length', metavar='Password Length', nargs=1, type=int, help='int')
    args = parser.parse_args()

    pwlen = args.Password_Length[0]
    
    a = more_special_characters.r3(int(pwlen))
    print(a)

