#!/usr/bin/python
#
# vop-1.3.0 
# FileCopyrightText: <text> 2022-2025 Matthew Buchanan Astley (mbastley@gmail.com, matthewbuchanan@astley.nl) </text> 
# Script to generate passwords with at least one lowercase, one uppercase letter and one special character.
# The password can be base64 encoded if needed. 

import os,sys
import secrets,base64
import argparse

class chstr():

    def array_for_shuffle(self):
        a = []
        for i in self:
            a.append(i)
        return(a)

    def shuffle_pw(self):
        a1 = secrets.SystemRandom("/dev/urandom")
        a1.shuffle(self)
        return(''.join(self))

    def rspec_char():
        a = [ '!','@','#','$','%','^','&','*','_','-','+','=','/','?','|']
        a1 = secrets.SystemRandom("/dev/urandom")
        return(a[a1.randint(0,len(a) -1 )])

     

    def upperR():
        a1 = [ 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z' ]
        a2 = secrets.SystemRandom("/dev/urandom")
        a3 = a2.randint(0,25)
        return(a1[a3])

    def lowerR():
        a2 = secrets.SystemRandom("/dev/urandom")
        a3 = a2.randint(0,25)
        a4 = [ 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z' ]
        return(a4[a3])

    def numbersR():
        a2 = secrets.SystemRandom("/dev/urandom")
        a3 = a2.randint(0,9)
        a4 = [ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' ]
        return(a4[a3])

    def rhsh(self):
        a = secrets.SystemRandom("/dev/urandom")
        a3 = a.randbytes(round((int(self)/777)*777))
        b = str(a3)
        d = base64.urlsafe_b64encode(bytes(b, encoding='UTF-8'))
        d4 = a.randint(0,((len(d) - 1) - int(self)))
        d5 = d4 + int(self)
        d1 = str(d[d4:d5]).lstrip('\'b').rstrip('\'')
        d1_2 = chstr.array_for_shuffle(d1)
        a.shuffle(d1_2) 
        d1_3 = ''.join(d1_2) 
        d1_1 = d1_3[2:len(d1) -1]
        return(d1_2)
 
    def prstr(self):
        a_1 = { "upper" : [], "lower" : [], "number" : [] } 

        for i in self:
            if i.isupper():
                a_1["upper"].append(i)
            elif i.islower():
                a_1["lower"].append(i)
            elif i.isalnum():
                a_1["number"].append(i)
 
        a4 = { "upper" :  len(a_1["upper"]), "lower" : len(a_1["lower"]), "number" : len(a_1["number"]) }
        a5 = int()
        
        a6 = []

        for i in a4.keys():
             a6.append(a4[i]) 
             #print("Ja", i, a4[i])
             a5 += a4[i] 
        
        a6.sort()

        # If one of the values in a6 is zero, one character must be subtracted from one of the others and added to the one that is zero
        # Additionally make sure at 4 characters the string consists of one l,u,n,sp character
        

        #print("Jaa", a4)
        #print("JAAAaaA", a_1)
        #print("JAAAa", len(a6), a6)
        
        if a4["upper"] == 0:
            a_1["upper"].append(chstr.upperR())
        if a4["lower"] == 0:
            a_1["lower"].append(chstr.lowerR())
        if a4["number"] == 0 and a4["upper"] > 1 :
            a_1["upper"].pop()
            a_1["upper"][-1] = chstr.rspec_char()
            a_1["number"].append(chstr.numbersR())

        # Commenting out this else statement from the control loop fixes the intermittent returning of one character less.
        ##else:
        
        #print("JAAAA", a_1)

        a_1["upper"][-1] = chstr.rspec_char()
        
        #
        # Check if there is a uc/lc/dgt array with more than 1 character to replace one character for a special character.
        # This adds more special characters if other arrays are > 1 :| 
        ##a_1_1 = a_1.keys()
        ##for i in a_1_1:
        ##    if len(a_1[i]) > 1:
        ##        a_1[i][-1] = chstr.rspec_char()
        
        #print("Jaa", a4)
        #print("Jaa", len(a4), a4)

        a7 = [] 
        for i in a4.keys():
            for ii in a_1[i]:
                a7.append(ii)

        #print("jAaa", self, len(a7), a7)

        if len(a7) != len(self):
            #print("JaAAa", len(a7), len(self))
            for i in range(0,(len(self) - len(a7))):
                a7.append(chstr.numbersR())
        
   
        return(chstr.shuffle_pw(a7))        

    def vop(self):
        return(chstr.prstr(chstr.rhsh(int(self))))
        

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('Password_Length', metavar='Password Length', nargs=1, type=int, help='int')
    parser.add_argument('Base64_Encoding', metavar='Base64 Encoding', nargs='?', const='False', type=int, help='1')
    args = parser.parse_args()

    pwlen = args.Password_Length[0]

    if args.Base64_Encoding == 1:
         a = base64.urlsafe_b64encode(bytes(chstr.vop(int(pwlen)),encoding='utf-8'))
         a1 = str(a)
         print(a1[2:len(a1)-1].strip('=_'))
    else:
         #print(chstr.vop(int(pwlen)))
         print(len(chstr.vop(int(pwlen))), chstr.vop(int(pwlen)))
