#!/usr/bin/python
#
# FileCopyrightText: <text> 2022-2025 Matthew Buchanan Astley (mbastley@gmail.com, matthewbuchanan@astley.nl) </text> 
# Version: 1.4.0 
# Script to generate passwords with at least one lowercase, one uppercase letter and one special character or more.
# The password can be base64 encoded if needed. 

import os,sys
import secrets,base64
import argparse
import logging

class chstr():

    logging.basicConfig(
        filename='vop_1.log',
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
  
    )


    def array_for_shuffle(self):
        a = []
        for i in self:
            a.append(i)
        return(a)

    def shuffle_pw(self):
        a1 = secrets.SystemRandom("/dev/urandom")
        a1.shuffle(self)
        return(''.join(self))

    def rspec_char():
        a = [ '!','@','#','$','%','^','&','*','_','-','+','=','/','?','|']
        a1 = secrets.SystemRandom("/dev/urandom")
        return(a[a1.randint(0,len(a) -1 )])

    def upperR():
        a1 = [ 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z' ]
        a2 = secrets.SystemRandom("/dev/urandom")
        a3 = a2.randint(0,25)
        return(a1[a3])

    def lowerR():
        a2 = secrets.SystemRandom("/dev/urandom")
        a3 = a2.randint(0,25)
        a4 = [ 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z' ]
        return(a4[a3])

    def numbersR():
        a2 = secrets.SystemRandom("/dev/urandom")
        a3 = a2.randint(0,9)
        a4 = [ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' ]
        return(a4[a3])

    def rhsh(self):
        a = secrets.SystemRandom("/dev/urandom")
        # Veel random bytes
        a3 = a.randbytes(int(self)*777)
        # Maak er een string van
        b = str(a3)
        # Base64 encode zonder rare karakters
        d = base64.urlsafe_b64encode(bytes(b, encoding='UTF-8')).decode()
        #logging.info("len b64 pw: " + str(len(d)))
        # Een random int om een willekeurige startpuntindex binnen de string d te hebben
        d4 = a.randint(0,((len(d)-1) - int(self)))
        #logging.info("Pw startindex: " + str(d4))
        # De eindindex van de passwordstring 
        d5 = d4 + int(self)
        #logging.info("Eindindex: " + str(d5))
        #d1 = str(d[d4:d5]).lstrip('\'b').rstrip('\'')  # Dit was het probleem van het verdwijnende karakter :|. Ok so this strips a regular b from the string. Use bytes.decode()
        d1 = str(d[d4:d5])
        #logging.info("Pw selectie: " + str(d1))

        return(d1)

    def a_pop(self):
            for i in range(0,int(self[1])):
                self[0].pop()
            return(self[0])
 
    def a_range(self):
            a = []
            for i in range(0,self[1]):
                a.append(self[0][i])
            return(a)
  
    def c_spec(self):
            if self in [ '!','@','#','$','%','^','&','*','_','-','+','=','/','?','|']:
                return True 

    def sprinkle_special_characters_on_the_password(self):
            a1 = secrets.SystemRandom("/dev/urandom")
            a4 = []
            for iiii in self[0]:
                a4.append(iiii)

            a6 = []

            for i in range(0,self[1]):
                a6.append(a1.randint(0,len(self[0])-1))

            logging.info("Aantal randint: "+ str(a6))
            a6.pop()

            logging.info("Aantal randint na pop: "+ str(a6))

            for i in a6:
                a4[i] = chstr.rspec_char()
            
            a7 = []  
            for i in a4: 
                if chstr.c_spec(i) == True:
                    a7.append(i) 

            logging.info("pw "+ ''.join(a4))
            logging.info("spec c "+ str(len(a7)) + " " + str(a7))
            
            
            return(''.join(a4))   
 
    def prstr(self):

        a8 = [ chstr.upperR(), chstr.lowerR(), chstr.numbersR(), chstr.rspec_char() ]
        a9 = [ chstr.upperR(), chstr.lowerR(), chstr.numbersR() ]

        a17 = []

        # Shuffle the default characters array
        a18 = secrets.SystemRandom("/dev/urandom")
        a18.shuffle(a8) 

        #
        # For 1,2,3 characters randomly choose characters 
 
        if len(self) == 1: 
            a17_1 = a18.randint(0,3)
            a17 = a8[a17_1] 
        elif len(self) == 2:
            a17_1 = a18.randint(0,3)
            a17_2 = a18.randint(0,3)
            a17 = [ str(a8[a17_1]), str(a8[a17_2]) ]
        elif len(self) == 3:
            a17_1 = a18.randint(0,3)
            a17_2 = a18.randint(0,3)
            a17_3 = a18.randint(0,3)
            a17 = [ str(a8[a17_1]), str(a8[a17_2]), str(a8[a17_3]) ]
        else:
            for i in range(0,(len(self) -4)):
                a17.append(self[i])

            for i in a8:
                a17.append(i)

        for i in enumerate(a8):
            a = a18.randint(0,len(a17)-1)
            a17 

        return(chstr.shuffle_pw(a17))    
 
    def vop(self):
        return(chstr.prstr(chstr.rhsh(int(self))))
        

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('Password_Length', metavar='Password Length', nargs=1, type=int, help='int')
    parser.add_argument('-s', nargs='?', const='False', type=int, help='Add more special characters'  )
    parser.add_argument('Base64_Encoding', metavar='Base64 Encoding', nargs='?', const='False', type=int, help='1')
    args = parser.parse_args()

    pwlen = args.Password_Length[0]
    if args.Base64_Encoding == 1:
         a = base64.urlsafe_b64encode(bytes(chstr.vop(int(pwlen)),encoding='utf-8'))
         a1 = str(a)
         # Remove base64 characters 
         print(a1[2:len(a1)-1].strip('=_'))
    elif args.s:
         a = chstr.vop(int(pwlen))
         a1 = chstr.sprinkle_special_characters_on_the_password([a, args.s])
         print(a1) 
    else:
         print(chstr.vop(int(pwlen)))
